bridges = []

[[instances]]
name = "Basic Chat Public"
id = "__basic-chat-public"
dna_hash = "QmYtMYK9Q3p7eAKgZCoNNktZuECkFjaCXaii2ZzirtHEKt"
uri = "https://github.com/willemolding/basic-chat/releases/download/v0.1.0/basic-chat.dna.json"

[[UIs]]
name = "Basic Chat"
id = "basic-chat-ui"
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/willemolding/basic-chat/releases/download/v0.1.0/ui.zip"

[[UIs.instance_references]]
ui_handle = "basic-chat"
instance_id = "__basic-chat-public"
