bridges = []

[[instances]]
name = "holotxt"
id = "holotxt_instance"
dna_hash = "QmTXsdZR3YnNsn87WVdXcQTZGmqNyBv8ubKaKGYnz3nsNb"
uri = "https://github.com/kristoferlund/holotxt/releases/download/v0.0.1/holotxt_dna.dna.json"

[[UIs]]
name = "holotxt"
id = "holotxt_id" 
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/kristoferlund/holotxt/releases/download/v0.0.1/ui.zip"

[[UIs.instance_references]]
ui_handle = "holotxt"
instance_id = "holotxt_instance" 